// FormulaMatchingController.cs created with MonoDevelop
// User: luis at 12:57 09/05/2008

using System;
using System.Collections.Generic;

using System.Threading;

using Gtk;

using MathTextLibrary.Analisys;
using MathTextLibrary.Controllers;

using MathTextRecognizer.Controllers.Nodes;

namespace MathTextRecognizer.Controllers
{
	
	/// <summary>
	/// This class implements the controller for the formula construction 
	/// process.
	/// </summary>
	public class ParsingController : ControllerBase
	{
		private List<Token> startTokens;
		
		private string output;
		private bool parsingResult;
		
		private NodeView nodeContainer;
		
		private SyntacticalCoverNode currentNode;
	
		/// <summary>
		/// <c>FormulaMatchingController</c>'s contructor.
		/// </summary>
		public ParsingController(NodeView container) : base()
		{
			this.nodeContainer = container;
		}
		
#region Properties
		/// <value>
		/// Contains the output of the rules.
		/// </value>
		public string Output
		{
			get 
			{
				return output;
			}
		}

		/// <value>
		/// Contains a value that indicates if the syntactical analisys
		/// was successful.
		/// </value>
		public bool ParsingResult
		{
			get 
			{
				return parsingResult;
			}
		}
		
#endregion Properties
		
#region Public methods
		
		/// <summary>
		/// Sets the tokens used as data for the process.
		/// </summary>
		/// <param name="startTokens">
		/// A <see cref="List`1"/> containing the <see cref="Token"/> 
		/// instances generated by the lexical analisys stage.
		/// </param>
		public void SetStartTokens(List<Token> startTokens)
		{
			this.startTokens = startTokens;
		}
		
		/// <summary>
		/// Call point to start the processing.
		/// </summary>
		protected override void Process ()
		{
			MessageLogSentInvoker("===========================================");
			MessageLogSentInvoker(" Comenzando proceso de análisis sintáctico");
			MessageLogSentInvoker("===========================================");
			
			SyntacticalRule startRule = 
				SyntacticalRulesLibrary.Instance.StartRule;
			
			SyntacticalRulesLibrary.Instance.Matching += 
				new MatchingHandler(OnMatcherMatching);
			SyntacticalRulesLibrary.Instance.MatchingFinished += 
				new EventHandler(OnMatcherMatchingFinished);
			
			currentNode =
				new SyntacticalCoverNode(SyntacticalRulesLibrary.Instance.StartRule, 
				                         nodeContainer);
			nodeContainer.NodeStore.AddNode(currentNode);
			
			SuspendByStep();
			
			parsingResult = 
				startRule.Match(new TokenSequence(startTokens), out output);
			
			
			
			ProcessFinishedInvoker();
		}

		
#endregion Public methods
		
#region Private methods
		
		private void OnMatcherMatching(object sender, MatchingArgs args)
		{
			Application.Invoke(sender, args, OnMatcherMatchingInThread);			
			
			SuspendByStep();
		}
		
		private void OnMatcherMatchingInThread(object sender, EventArgs args)
		{
			
			MatchingArgs margs = args as MatchingArgs;			
			
			SyntacticalCoverNode newNode =
				new SyntacticalCoverNode(margs.Matcher, nodeContainer);
			
			NodeBeingProcessedInvoker(newNode);
			
			if(currentNode == null)
			{
				this.nodeContainer.NodeStore.AddNode(newNode);
			}
			else
			{
				currentNode.AddChild(newNode);
			}
			
			nodeContainer.ColumnsAutosize();
			currentNode = newNode;
			currentNode.Select();
			nodeContainer.ExpandAll();		
			
		}
		
		private void OnMatcherMatchingFinished(object sender, EventArgs args)
		{
			Application.Invoke(OnMatcherFinishedInThread);
		}
		
		private void OnMatcherFinishedInThread(object sender, EventArgs args)
		{
			
			if(currentNode.Parent !=null)
			{
				currentNode =  currentNode.Parent as SyntacticalCoverNode;
				currentNode.Select();
			}
		}
		
				
		
#endregion Private methods
		
	}
}

